### ISSUE TITLE
[design] main home, calendar, todo component 디자인 수정

### ISSUE THREAD

**Issue by inaemon** [Kusitms-30th-LetsCareer-B/LetsCareer-FE#65]
### 📝Issue 설명
> main home, calendar, todo component 디자인 세부 수정

### 🔨작업 상세내용
- [x] main home 디자인 수정
- [x] calendar 디자인 수정
- [x] todo component 디자인 수정
